{% set name = "general_robotics_toolbox" %}
{% set version = "0.7.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/rpiRobotics/rpi_general_robotics_toolbox_py/archive/refs/tags/{{ version }}.tar.gz
  sha256: 25921bd38ff2130478a6ee1f373a44adeb0da700611088cbbd656e0568b0a690

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - numpy
    - pyyaml
  run:
    - python >={{ python_min }}
    - numpy
    - pyyaml

test:
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - test/
  imports:
    - pytest
  commands:
    - pytest test/ --verbose --ignore test/test_urdf_loader.py

about:
  home: https://github.com/rpiRobotics/rpi_general_robotics_toolbox_py
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python robotics toolbox

extra:
  recipe-maintainers:
    - johnwason
